title = "IVPN"
theme = "ivpn-v3"
summaryLength = 35
disableKinds = ["sitemap", "taxonomy"]

[pagination]
  pagerSize = 8

[markup.highlight]
  noClasses = false
  codeFences = true
  guessSyntax = true
  style = "monokai"

DefaultContentLanguage = "en"
defaultContentLanguageInSubdir = true 

[languages]
  [languages.en]
    locale = "en"
    contentDir = 'content/en'
    label = 'English'
    direction = 'ltr'
    weight = 1
  [languages.es]
    locale = "es"
    contentDir = 'content/es'
    label = 'Español'

    direction = 'ltr'
    weight = 2

[markup.goldmark.renderer]
    unsafe= true

[outputs]
    home = ["HTML"]
    section = ["JSON", "HTML", "RSS"]

[params]
    environment = "development"    
    images = ["/images-static/uploads/og_1200-627.png"]
    cdnUrl = ""
    matomoEnabled = false
    matomoUrl = "https://stats.ivpn.net"
    matomoSiteId = 1

[taxonomies]
  category = "categories"
  tag = "tags"
  authors = "authors"

[permalinks]
  categories = "/blog/categories/:slug/"
  tags = "/blog/tags/:slug/"
  authors = "/blog/authors/:slug/"

[related]
  threshold = 80
  includeNewer = true
  toLower = false
  [[related.indices]]
  name = "categories"
  weight = 90
  [[related.indices]]
  name = "tags"
  weight = 40
  [[related.indices]]
  name  = "date"
  weight = 60
  pattern = "200601"