baseURL = "https://ivpn.net"

[params]
    cdnUrl = ""
    environment = "staging"     
    matomoEnabled = false
    matomoUrl = "https://stats.ivpn.net"
    matomoSiteId = 1
    mailXURL = "https://app.staging.mailx.net"
    modDNSURL = "https://app.staging.ivpndns.net"
    portmasterURL = "https://account.safing.io"