baseURL = "https://www.ivpn.net"

[params]
    cdnUrl = ""
    environment = "production"     
    matomoEnabled = true
    matomoUrl = "https://stats.ivpn.net"
    matomoSiteId = 1
    mailXURL = "https://mailx.net"
    modDNSURL = "https://moddns.net"
    portmasterURL = "https://account.safing.io"